DROP VIEW IF EXISTS ToppingPopularity;
DROP VIEW IF EXISTS ProfitByPizza;
DROP VIEW IF EXISTS ProfitByOrderType;

DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS BASEPRICE;
DROP TABLE IF EXISTS DISCOUNT;
DROP TABLE IF EXISTS TOPPING;
DROP TABLE IF EXISTS ORDERTABLE;
DROP TABLE IF EXISTS PIZZA;
DROP TABLE IF EXISTS PIZZA_TOPPING;
DROP TABLE IF EXISTS PIZZA_DISCOUNT;
DROP TABLE IF EXISTS ORDER_DISCOUNT;
DROP TABLE IF EXISTS PICKUP;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS DINEIN;
